---
- hosts: all

  vars_files:
    - ../config.yml

  pre_tasks:
    - include: tasks/init.yml
    - include: tasks/php-versions.yml

  roles:
    # Essential roles.
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.apache, tags: ['apache'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-pecl, tags: ['php'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.composer, tags: ['composer'] }
    - { role: geerlingguy.drush, tags: ['drush'] }

    # Roles to be installed conditionally.
    - {
      role: geerlingguy.memcached,
      when: '"memcached" in installed_extras'
    }
    - {
      role: geerlingguy.php-memcached,
      when: '"memcached" in installed_extras'
    }
    - {
      role: geerlingguy.php-xdebug,
      when: '"xdebug" in installed_extras'
    }
    - {
      role: geerlingguy.php-xhprof,
      when: '"xhprof" in installed_extras'
    }
    - {
      role: geerlingguy.phpmyadmin,
      when: '"phpmyadmin" in installed_extras'
    }
    - {
      role: geerlingguy.daemonize,
      when: '"mailhog" in installed_extras'
    }
    - {
      role: geerlingguy.mailhog,
      when: '"mailhog" in installed_extras'
    }
    - {
      role: geerlingguy.java,
      when: '"solr" in installed_extras'
    }
    - {
      role: geerlingguy.solr,
      when: '"solr" in installed_extras'
    }

  tasks:
    - include: tasks/www.yml
    - include: tasks/drupal.yml
      when: build_from_makefile
